[alias]
b = "build --release"
c = "check"
t = "test -- --nocapture"
r = "run"
u = "update"
f = "clippy --fix --all-targets --all-features --allow-staged --allow-dirty"

[build]
rustc-wrapper = "sccache"

[profile.dev]
debug = false
